# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '8.0'

target 'masamon' do
    use_frameworks!

    pod 'RealmSwift'
    
    pod 'GradientCircularProgress', :git => 'https://github.com/keygx/GradientCircularProgress'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
    
end

