"""empty message

Revision ID: 43b8be8e03be
Revises: d2e952c26ebe
Create Date: 2018-03-06 15:16:39.353786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b8be8e03be'
down_revision = 'd2e952c26ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shift_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shift_category_id'], ['shiftcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shift')
    # ### end Alembic commands ###
