"""empty message

Revision ID: 607d2eb093d9
Revises: 7843d83bc266
Create Date: 2018-03-06 14:44:15.983426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607d2eb093d9'
down_revision = '7843d83bc266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('employee', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employee', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'role_id')
    op.drop_table('role')
    # ### end Alembic commands ###
