"""empty message

Revision ID: 7843d83bc266
Revises: 47ceb9d058f8
Create Date: 2018-03-06 04:11:10.555396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7843d83bc266'
down_revision = '47ceb9d058f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('salary', 'employee_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('salary', 'shifttable_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('shifttable', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shifttable', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('salary', 'shifttable_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('salary', 'employee_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('employee', 'company_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
