"""empty message

Revision ID: 874e6d8f7dee
Revises: 
Create Date: 2018-03-06 00:18:26.697593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '874e6d8f7dee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('daytime_start', sa.Time(), nullable=True),
    sa.Column('daytime_end', sa.Time(), nullable=True),
    sa.Column('daytime_hourly_wage', sa.Integer(), nullable=True),
    sa.Column('night_start', sa.Time(), nullable=True),
    sa.Column('night_end', sa.Time(), nullable=True),
    sa.Column('night_hourly_wage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Employee')
    # ### end Alembic commands ###
