"""empty message

Revision ID: 899bf057c55f
Revises: 
Create Date: 2018-03-05 16:39:38.825808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '899bf057c55f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hoge', sa.String(length=255), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'hoge')
    # ### end Alembic commands ###
