"""empty message

Revision ID: 9404079aa588
Revises: a9dd52350cd1
Create Date: 2018-03-06 01:08:40.427952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9404079aa588'
down_revision = 'a9dd52350cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Employee', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Employee', 'Company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Employee', type_='foreignkey')
    op.drop_column('Employee', 'company_id')
    # ### end Alembic commands ###
