"""empty message

Revision ID: b514b6209c7b
Revises: 9404079aa588
Create Date: 2018-03-06 01:25:58.772057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b514b6209c7b'
down_revision = '9404079aa588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Company', ['code'])
    op.create_unique_constraint(None, 'Company', ['name'])
    op.create_unique_constraint(None, 'Employee', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Employee', type_='unique')
    op.drop_constraint(None, 'Company', type_='unique')
    op.drop_constraint(None, 'Company', type_='unique')
    # ### end Alembic commands ###
