"""empty message

Revision ID: d2e952c26ebe
Revises: 2f9f58d0a259
Create Date: 2018-03-06 15:14:11.334620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e952c26ebe'
down_revision = '2f9f58d0a259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colorscheme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colorscheme')
    # ### end Alembic commands ###
