"""empty message

Revision ID: 4e3a8e971199
Revises: 691ea2337388
Create Date: 2018-03-23 15:53:06.260348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3a8e971199'
down_revision = '691ea2337388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('thing', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thing', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thing', type_='foreignkey')
    op.drop_column('thing', 'book_id')
    op.drop_table('book')
    # ### end Alembic commands ###
