"""empty message

Revision ID: 6aa238f6e22f
Revises: 4e3a8e971199
Create Date: 2018-03-23 16:22:06.804266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6aa238f6e22f'
down_revision = '4e3a8e971199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thing')
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('thing',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('item1', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('item2', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='thing_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
