# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'masamon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for masamon
	pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'feature/Xcode9-Swift3_2'
	pod 'SwiftyJSON'
	pod 'Alamofire', '~> 4.5'
end
